### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by fanglangxinghai**
simple Chinese translation

### CODE REVIEW

**Comment by KUR-creative** [comment]
I will keep the default config.json in English, UTF-8 encoding. The uploaded config.json will be saved as config-chn-GB2312.json. I'll take care of it for you.

Later, I'll upload Chinese, Windows version of SZMC on the [release page](https://github.com/KUR-creative/SickZil-Machine/releases) using config-chn-GB2312.json as config.json. Please download it, test it, and let me know if it works. Because I don't have Chinese Windows, so I can't test it myself.

If the downloaded Chinese-Windows version of SZMC work well in your machine, then I merge your pull request.

**Comment by fanglangxinghai** [comment]
> I will keep the default config.json in English, UTF-8 encoding. The uploaded config.json will be saved as config-chn-GB2312.json. I'll take care of it for you.
> 
> Later, I'll upload Chinese, Windows version of SZMC on the [release page](https://github.com/KUR-creative/SickZil-Machine/releases) using config-chn-GB2312.json as config.json. Please download it, test it, and let me know if it works. Because I don't have Chinese Windows, so I can't test it myself.
> 
> If the downloaded Chinese-Windows version of SZMC work well in your machine, then I merge your pull request.

ok！

**Comment by KUR-creative** [comment]
Uploaded cpu version
https://github.com/KUR-creative/SickZil-Machine/releases/download/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-chn.zip

and gpu version
https://github.com/KUR-creative/SickZil-Machine/releases/download/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-gpu-chn.zip

Please download and test them. If these works well, tell me, I will merge PR. Thank you!

**Comment by fanglangxinghai** [comment]
> Uploaded cpu version
> https://github.com/KUR-creative/SickZil-Machine/releases/download/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-cpu-chn.zip
> 
> and gpu version
> https://github.com/KUR-creative/SickZil-Machine/releases/download/v0.1.1-pre0/SickZil-Machine-0.1.1-pre0-win64-gpu-chn.zip
> 
> Please download and test them. If these works well, tell me, I will merge PR. Thank you!

I have tested cpu version and gpu version.Both are very perfect.Please update Chinese version to make more people easily use this software!

Besides,there's an advice from my friend.He said since we just need to remove the japanese text from the manga.If you can do some work about **japanese words** and the **common fonts** of japanese, will you make the software more **precisely**  when doing mask work?  Anyway, it's just our advice (we don't even know any programming knowledge),if you think it's not a good idea,just forget it!

**Pull request merged**
